name: Push plugins changes to DITA-OT repo

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up environmental variables from properties file
        id: SetEnvVars
        run: |
          export $(grep -v '^#' action.properties | xargs)
          echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"
          echo "PUBLISHING_ENGINE=$PUBLISHING_ENGINE" >> "$GITHUB_ENV"
          echo "Publishing to '$BRANCH' branch with engine '$PUBLISHING_ENGINE'"

      - name: Set up Git
        run: |
          echo git --version
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}

      - name: Clone the target repository and checkout the branch
        run: |
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git dita-ot-repo
          cd dita-ot-repo
          git checkout $BRANCH

      - name: Sync files with rsync
        run: |
          rsync -av --delete --exclude .git/ plugins/ dita-ot-repo/$PUBLISHING_ENGINE/plugins/

      - name: Commit and push changes to the target repository
        run: |
          cd dita-ot-repo/
          git add .
          git commit -m "Sync changes from xslt-stylesheets repository"
          git push https://${{ secrets.USER_NAME }}:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git HEAD:$BRANCH
