name: Push plugins changes to DITA-OT repo

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up environmental variables from properties file
        id: SetEnvVars
        run: |
          while IFS='=' read -r key value
            do
              echo "${key}=${value}" >> "$GITHUB_ENV"
          done < "action.properties"
          CURR_REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "CURR_REPO=$CURR_REPO" >> "$GITHUB_ENV"
          echo "Publishing to the repo '$REPO_NAME' to '$BRANCH' branch with engine '$PUBLISHING_ENGINE'"

      - name: Set up Git
        run: |
          echo git --version
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}

      - name: Clone the target repository and checkout the branch
        run: |
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/$REPO_NAME.git $REPO_NAME
          cd $REPO_NAME
          git checkout $BRANCH

      - name: Sync files with rsync
        run: |
          rsync -av --delete --exclude .git/ plugins/ $REPO_NAME/$PUBLISHING_ENGINE/plugins/

      - name: Commit and push changes to the target repository
        run: |
          cd $REPO_NAME/
          git add .
          git commit -m "Sync changes from $CURR_REPO repository"
          git push https://${{ secrets.USER_NAME }}:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/$REPO_NAME.git HEAD:$BRANCH
