name: Push plugins changes to DITA-OT repo

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up bash script to read from properties file
        id: SetEnvVars
        run: |
          export $(grep -v '^#' action.properties | xargs)
          echo "BRANCH=$BRANCH" >> "$GITHUB_OUTPUT"
          echo "PUBLISHING_ENGINE=$PUBLISHING_ENGINE" >> "$GITHUB_OUTPUT"
          echo "Publishing to \"$BRANCH\" branch with engine $PUBLISHING_ENGINE"

      - name: Set up Git
        run: |
          echo git --version
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}

      - name: Clone the target repository
        env:
          branch: ${{ steps.SetEnvVars.outputs.BRANCH }}
        run: |
          git clone https://github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git dita-ot-repo
          cd dita-ot-repo
          git checkout $branch

      - name: Sync files with rsync
        env:
          engine: ${{ steps.SetEnvVars.outputs.PUBLISHING_ENGINE }}
        run: |
          rsync -av --exclude .git/ plugins/ dita-ot-repo/$engine/plugins/

      - name: Commit and push changes to the target repository
        env:
          branch: ${{ steps.SetEnvVars.outputs.BRANCH }}
        run: |
          cd dita-ot-repo/
          git add .
          git commit -m "Sync changes from source repository"
          git push https://${{ secrets.USER_NAME }}:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git HEAD:$branch
