name: Push plugins changes to DITA-OT repo

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up bash script to read from properties file
        run: |
          BRANCH=$(grep -oP '^BRANCH=\K.*' action.properties)
          PUBLISHING_ENGINE=$(grep -oP '^PUBLISHING_ENGINE=\K.*' action.properties)
          echo "Publishing to \"$BRANCH\" branch with engine $PUBLISHING_ENGINE"

      - name: Set up Git
        run: |
          echo git --version
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}

      - name: Clone the target repository
        run: |
          git clone https://github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git dita-ot-repo
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Sync files with rsync
        run: |
          rsync -av --exclude .git/ plugins/ dita-ot-repo/$PUBLISHING_ENGINE/plugins/

      - name: Commit and push changes to the target repository
        run: |
          cd dita-ot-repo/
          git add .
          git commit -m "Sync changes from source repository"
          git push https://${{ secrets.USER_NAME }}:${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.USER_NAME }}/dita-ot-repo.git HEAD:$BRANCH
