name: Validate properties before pushing to DITA-OT repo

on:
  pull_request:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  validate_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Read and set up environmental variables from properties file
        run: |
          while IFS='=' read -r key value
            do
              echo "${key}=${value}" >> "$GITHUB_ENV"
          done < "action.properties"

      - name: Check access to Git
        run: |
          git ls-remote https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/$REPO_NAME.git > /dev/null 2>&1
          EXIT_CODE=$?
