name: Validate properties before pushing to DITA-OT repo

on:
  pull_request:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  validate_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Read and set up environmental variables from properties file
        run: |
          while IFS='=' read -r key value
            do
              echo "${key}=${value}" >> "$GITHUB_ENV"
          done < "action.properties"

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Check access to DITA-OT repo
        run: |
          git ls-remote https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ github.actor }}/$REPO_NAME.git > /dev/null 2>&1
          EXIT_CODE=$?
          if [[ $EXIT_CODE == '0' ]]; then
            echo "Git repo '$REPO_NAME.git' can be accessed"
          elif [[ $EXIT_CODE == '2' ]]; then
            echo "Git repo '$REPO_NAME.git' cannot be accessed"
            exit 1
          fi

      - name: Check Branch existence
        run: |
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ github.actor }}/$REPO_NAME.git $REPO_NAME
          cd $REPO_NAME
          git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1
          EXIT_CODE=$?
          if [[ $EXIT_CODE == '0' ]]; then
            echo "Git branch '$BRANCH' exists"
          elif [[ $EXIT_CODE == '2' ]]; then
            echo "Git branch '$BRANCH' does not exist"
            exit 1
          fi
